[0m15:15:03.430823 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1021839d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104193280>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104193c10>]}


============================== 15:15:03.433271 | d8660bab-6e95-4446-80e4-0405001d1a74 ==============================
[0m15:15:03.433271 [info ] [MainThread]: Running with dbt=1.8.1
[0m15:15:03.433653 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/shrikanth/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt init', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m15:15:03.458240 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': PosixPath('/Users/shrikanth/.dbt')}
[0m15:15:03.458566 [info ] [MainThread]: Creating dbt configuration folder at 
[0m15:15:15.596869 [debug] [MainThread]: Starter project path: /Users/shrikanth/.asdf/installs/python/3.9.12/lib/python3.9/site-packages/dbt/include/starter_project
[0m15:15:15.606661 [info ] [MainThread]: 
Your new dbt project "pgmigrate" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m15:15:15.607481 [info ] [MainThread]: Setting up your profile.
[0m15:15:15.608658 [error] [MainThread]: Encountered an error:
Runtime Error
  No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli
[0m15:15:15.939905 [debug] [MainThread]: Resource report: {"command_name": "init", "command_wall_clock_time": 12.547235, "process_user_time": 0.577336, "process_kernel_time": 0.074119, "process_mem_max_rss": "90537984", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m15:15:15.940931 [debug] [MainThread]: Command `dbt init` failed at 15:15:15.940778 after 12.55 seconds
[0m15:15:15.941590 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1021839d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10414f790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104185430>]}
[0m15:15:15.942189 [debug] [MainThread]: Flushing usage events
