[0m16:25:58.085133 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1023cdb80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1043e1280>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1043e1970>]}


============================== 16:25:58.087082 | 720a4444-688a-4ecf-a4cd-c1db1d185809 ==============================
[0m16:25:58.087082 [info ] [MainThread]: Running with dbt=1.8.1
[0m16:25:58.087463 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/shrikanth/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': '/Users/shrikanth/Shrikanth/dbt-helloworld/pgmigrate/logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt ls', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:25:58.089081 [error] [MainThread]: Encountered an error:
Runtime Error
  Could not find profile named 'pgmigrate'
[0m16:25:58.089867 [debug] [MainThread]: Resource report: {"command_name": "list", "command_wall_clock_time": 0.03750879, "process_user_time": 0.546413, "process_kernel_time": 0.051485, "process_mem_max_rss": "85114880", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m16:25:58.090272 [debug] [MainThread]: Command `dbt ls` failed at 16:25:58.090212 after 0.04 seconds
[0m16:25:58.090517 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1023cdb80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10441f1f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10441f250>]}
[0m16:25:58.090750 [debug] [MainThread]: Flushing usage events
[0m16:26:45.024386 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10667dbb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108693eb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108693730>]}


============================== 16:26:45.026952 | bc591e0d-afc5-4f31-9061-b5d92784cddb ==============================
[0m16:26:45.026952 [info ] [MainThread]: Running with dbt=1.8.1
[0m16:26:45.027343 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': '/Users/shrikanth/Shrikanth/dbt-helloworld/pgmigrate/logs', 'profiles_dir': '/Users/shrikanth/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt run', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m16:26:45.029030 [error] [MainThread]: Encountered an error:
Runtime Error
  Could not find profile named 'pgmigrate'
[0m16:26:45.030442 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.041365918, "process_user_time": 0.557151, "process_kernel_time": 0.077928, "process_mem_max_rss": "85245952", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m16:26:45.030842 [debug] [MainThread]: Command `dbt run` failed at 16:26:45.030786 after 0.04 seconds
[0m16:26:45.031099 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10667dbb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10806ab20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1083652b0>]}
[0m16:26:45.031340 [debug] [MainThread]: Flushing usage events
